name: manim-online
channels:
  - conda-forge
dependencies:
  - python=3.11
  - manim==0.20.1
  - ffmpeg
  - pip
  - jupyterlab
  - ipywidgets
  - pip:
      - manim-slides
      - jupyterlab-mathjax3
